import AdminPageHeader from "@/components/admin/AdminPageHeader";
import BriefPanel from "@/components/admin/BriefPanel";

export default function BriefPage() {
  return (
    <div>
      <AdminPageHeader
        title="Daily Brief"
        subtitle="5 music moments worth posting today — generated by Claude."
      />
      <BriefPanel />
    </div>
  );
}
